package com.cs525.reversi.models;

public enum AlgorithmMode {
	AB_PRUNING_WITH_MINIMAL_WEIGHTS,//LOW DEPTH, PRUNING, 3 MAIN WEIGHTS
	AB_PRUNING_WITH_MAXIMAL_WEIGHTS,//LOW DEPTH, PRUNING, ALL WEIGHTS
	AB_PRUNING_WITH_HIGH_DEPTH, // HIGH DEPTH WITH 2 WEIGHTS
	NO_PRUNING_WITH_MINIMAL_WEIGHTS,//LOW DEPTH, NO PRUNING, 3 MAIN WEIGHTS
	NO_PRUNING_WITH_MAXIMAL_WEIGHTS,//LOW DEPTH, NO PRUNING, ALL WEIGHTS
	NO_PRUNING_WITH_HIGH_DEPTH, // NO PRUNING, HIGH DEPTH WITH 2 WEIGHTS
	
	MINIMAL_WEIGHTS,
	MAXIMAL_WEIGHTS,
	NO_WEIGHTS,
	

}
